"use client";
import { LanguageSwitcher } from "@/components/language-provider";
import { type Language } from "@/lib/translations";
import { useEffect, useState } from "react";
import { Eye, ImagePlus, Package, Pencil, Search, Trash2, X } from "lucide-react";
import { defaultCatalog, readCatalog, saveCatalog, type CatalogProduct } from "@/lib/catalog";
import { defaultContent, defaultContentForLanguage, defaultEvents, readContent, readEvents, saveContent, saveEvents, type EventPost, type StoreContent } from "@/lib/store-content";

type Order = { id: string; customer: string; phone: string; address: string; item: string; image: string; total: string; status: string };
const seedOrders: Order[] = [
  { id: "US-0142", customer: "Ma Thiri", phone: "09 777 000 112", address: "Bahan Township, Yangon", item: "Cocoon Hanging Chair · L × 1", image: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=300&q=80", total: "385,000 MMK", status: "Pending payment" },
  { id: "US-0141", customer: "Ko Htet", phone: "09 784 220 819", address: "Hlaing Township, Yangon", item: "Round Rattan Coffee Table · M × 1", image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=300&q=80", total: "245,000 MMK", status: "Confirmed" },
];
const newProduct = (): CatalogProduct => ({ id: crypto.randomUUID(), name: "", category: "Seating", price: "", sizes: ["M"], image: "", description: "" });
const newEvent = (): EventPost => ({ id: crypto.randomUUID(), title: "", date: "", image: "", button: "Read more" });

export default function AdminPage() {
  const [contentLanguage, setContentLanguage] = useState<Language>("en");
  useEffect(() => { setContent(readContent(contentLanguage)); }, [contentLanguage]);
  const [ok, setOk] = useState(false); const [user, setUser] = useState(""); const [pass, setPass] = useState(""); const [tab, setTab] = useState("overview"); const [message, setMessage] = useState("");
  const [categories, setCategories] = useState(["Seating", "Tables", "Decor"]); const [categoryName, setCategoryName] = useState("");
  const [catalog, setCatalog] = useState<CatalogProduct[]>(defaultCatalog); const [product, setProduct] = useState<CatalogProduct>(newProduct()); const [productEdit, setProductEdit] = useState<string | null>(null);
  const [events, setEvents] = useState<EventPost[]>(defaultEvents); const [eventPost, setEventPost] = useState<EventPost>(newEvent()); const [eventEdit, setEventEdit] = useState<string | null>(null);
  const [content, setContent] = useState<StoreContent>(defaultContent); const [orders, setOrders] = useState<Order[]>(seedOrders); const [selected, setSelected] = useState<Order | null>(null); const [adminSearch, setAdminSearch] = useState("");
  useEffect(() => { setOk(localStorage.getItem("uksein_admin") === "yes"); setCatalog(readCatalog()); setEvents(readEvents()); setContent(readContent()); const c = localStorage.getItem("uksein_categories"), o = localStorage.getItem("uksein_orders"); if (c) setCategories(JSON.parse(c)); if (o) setOrders(JSON.parse(o)); }, []);
  const persistCategories = (items: string[]) => { setCategories(items); localStorage.setItem("uksein_categories", JSON.stringify(items)); };
  const imageToData = (file: File | undefined, target: "product" | "event" | "hero", index = 0) => { if (!file) return; const reader = new FileReader(); reader.onload = () => { const image = String(reader.result); if (target === "product") setProduct({ ...product, image }); else if (target === "event") setEventPost({ ...eventPost, image }); else { const heroImages = [...content.home.heroImages]; heroImages[index] = image; setContent({ ...content, home: { ...content.home, heroImages } }); } }; reader.readAsDataURL(file); };
  const saveProduct = (e: React.FormEvent) => { e.preventDefault(); if (!product.name || !product.price || !product.image) return; const next = productEdit ? catalog.map((x) => x.id === productEdit ? product : x) : [...catalog, product]; setCatalog(next); saveCatalog(next); setProduct(newProduct()); setProductEdit(null); setMessage("Product saved."); };
  const saveEvent = (e: React.FormEvent) => { e.preventDefault(); if (!eventPost.title || !eventPost.image) return; const next = eventEdit ? events.map((x) => x.id === eventEdit ? eventPost : x) : [...events, eventPost]; setEvents(next); saveEvents(next); setEventPost(newEvent()); setEventEdit(null); setMessage("Event saved."); };
  const saveOrder = (order: Order) => { const next = orders.map((x) => x.id === order.id ? order : x); setOrders(next); localStorage.setItem("uksein_orders", JSON.stringify(next)); setSelected(order); };
  const nav = [["overview", "Overview"], ["products", "Products"], ["categories", "Categories"], ["orders", "Orders"], ["events", "Events & blogs"], ["content", "All storefront content"]];
  const matches = (value: string) => !adminSearch.trim() || value.toLowerCase().includes(adminSearch.trim().toLowerCase());
  if (!ok) return <main className="login-page"><form className="login-card" onSubmit={(e) => { e.preventDefault(); if (user === "admin" && pass === "UkSein@2026") { localStorage.setItem("uksein_admin", "yes"); setOk(true); } }}><span className="brand-mark">U</span><p className="eyebrow">UK SEIN · ADMIN</p><h1>Sign in</h1><label>Username<input value={user} onChange={(e) => setUser(e.target.value)} required /></label><label>Password<input type="password" value={pass} onChange={(e) => setPass(e.target.value)} required /></label><button className="gold-button">Sign in</button></form></main>;
  return <main className="admin"><header><div className="brand"><span className="brand-mark">U</span><b>UK SEIN <small>ADMIN</small></b></div><label className="admin-global-search"><Search size={16} /><input aria-label="Search this admin section" value={adminSearch} onChange={(event) => setAdminSearch(event.target.value)} placeholder="Search this section..." /></label><div className="admin-head-actions"><LanguageSwitcher /><a href="/">View storefront</a><button onClick={() => { localStorage.removeItem("uksein_admin"); setOk(false); }}>Sign out</button></div></header><div className="admin-body"><aside>{nav.map(([id, label]) => <button key={id} className={tab === id ? "selected" : ""} onClick={() => { setTab(id); setMessage(""); }}>{label}{id === "orders" && <i>{orders.length}</i>}</button>)}</aside><section className="dashboard">
    {tab === "overview" && <><p className="eyebrow">DASHBOARD</p><h1>Good morning.</h1><div className="stats"><div><span>Orders</span><b>{orders.length}</b><small>Manage order status</small></div><div><span>Products</span><b>{catalog.length}</b><small>Create, edit or delete</small></div><div><span>Events</span><b>{events.length}</b><small>Published posts</small></div></div><h2>Recent orders</h2><OrderList rows={orders.filter((order) => matches(`${order.id} ${order.customer} ${order.item} ${order.status}`))} choose={setSelected} /></>}
    {tab === "products" && <><p className="eyebrow">CATALOG</p><h1>Products</h1><div className="admin-product-layout"><ProductForm value={product} categories={categories} editing={!!productEdit} setValue={setProduct} chooseImage={(file) => imageToData(file, "product")} submit={saveProduct} cancel={() => { setProduct(newProduct()); setProductEdit(null); }} /><div className="admin-catalog"><h3>Product list · {catalog.filter((product) => matches(`${product.name} ${product.category} ${product.price} ${product.description}`)).length}</h3>{catalog.filter((product) => matches(`${product.name} ${product.category} ${product.price} ${product.description}`)).map((x) => <article key={x.id}><img src={x.image} alt={x.name} /><div><b>{x.name}</b><small>{x.category} · {x.sizes.join(" / ")}</small><em>{x.price}</em></div><button onClick={() => { setProduct(x); setProductEdit(x.id); }}><Pencil size={17} /></button><button onClick={() => { const n = catalog.filter((p) => p.id !== x.id); setCatalog(n); saveCatalog(n); }}><Trash2 size={17} /></button></article>)}</div></div></>}
    {tab === "categories" && <><p className="eyebrow">CATALOG</p><h1>Categories</h1><form className="category-add" onSubmit={(e) => { e.preventDefault(); const n = categoryName.trim(); if (n && !categories.includes(n)) persistCategories([...categories, n]); setCategoryName(""); }}><input value={categoryName} onChange={(e) => setCategoryName(e.target.value)} placeholder="New category name" /><button className="gold-button">Create category</button></form><div className="category-cards">{categories.filter((category) => matches(category)).map((x) => <div key={x}><Package /><h2>{x}</h2><p>Product category</p><span className="crud-actions"><button onClick={() => { const n = window.prompt("Category name", x)?.trim(); if (n && !categories.includes(n)) persistCategories(categories.map((c) => c === x ? n : c)); }}><Pencil size={15} /> Edit</button><button onClick={() => persistCategories(categories.filter((c) => c !== x))}><Trash2 size={15} /> Delete</button></span></div>)}</div></>}
    {tab === "orders" && <><p className="eyebrow">SALES</p><h1>Orders</h1><OrderList rows={orders.filter((order) => matches(`${order.id} ${order.customer} ${order.item} ${order.status}`))} choose={setSelected} /></>}
    {tab === "events" && <><p className="eyebrow">EVENTS & BLOGS</p><h1>{eventEdit ? "Edit event" : "Create event"}</h1><EventForm value={eventPost} setValue={setEventPost} chooseImage={(file) => imageToData(file, "event")} submit={saveEvent} editing={!!eventEdit} cancel={() => { setEventPost(newEvent()); setEventEdit(null); }} /><div className="admin-events">{events.filter((event) => matches(`${event.title} ${event.date} ${event.button}`)).map((x) => <article key={x.id}><img src={x.image} alt="" /><div><small>{x.date}</small><b>{x.title}</b></div><button onClick={() => { setEventPost(x); setEventEdit(x.id); }}><Pencil size={17} /></button><button onClick={() => { const n = events.filter((p) => p.id !== x.id); setEvents(n); saveEvents(n); }}><Trash2 size={17} /></button></article>)}</div></>}
    {tab === "content" && <form className="product-form content-form" onSubmit={(e) => { e.preventDefault(); saveContent(content, contentLanguage); setMessage("Storefront content saved."); }}><p className="eyebrow">DYNAMIC CONTENT</p><h1>All storefront text</h1><label>Content language<select value={contentLanguage} onChange={(event) => setContentLanguage(event.target.value as Language)}><option value="en">English</option><option value="my">မြန်မာ</option></select></label><p>Save changes before switching the content language.</p><h3>Home page</h3><Fields data={Object.fromEntries(Object.entries(content.home).filter((entry): entry is [string, string] => typeof entry[1] === "string"))} update={(key, value) => setContent({ ...content, home: { ...content.home, [key]: value } })} /><HeroImages images={content.home.heroImages} update={(heroImages) => setContent({ ...content, home: { ...content.home, heroImages } })} upload={(file, index) => imageToData(file, "hero", index)} /><h3>About page</h3><Fields data={content.about} update={(key, value) => setContent({ ...content, about: { ...content.about, [key]: value } })} /><h3>Events page</h3><Fields data={content.events} update={(key, value) => setContent({ ...content, events: { ...content.events, [key]: value } })} /><button className="gold-button">Save changes</button><button type="button" onClick={() => { const reset = defaultContentForLanguage(contentLanguage); setContent(reset); saveContent(reset, contentLanguage); setMessage("Content reset to defaults."); }}>Reset content</button></form>}
    {message && <small className="save-note">{message}</small>}
  </section></div>{selected && <OrderModal order={selected} close={() => setSelected(null)} save={saveOrder} remove={() => { const n = orders.filter((x) => x.id !== selected.id); setOrders(n); localStorage.setItem("uksein_orders", JSON.stringify(n)); setSelected(null); }} />}</main>;
}

function ProductForm({ value, categories, editing, setValue, chooseImage, submit, cancel }: { value: CatalogProduct; categories: string[]; editing: boolean; setValue: (x: CatalogProduct) => void; chooseImage: (x?: File) => void; submit: (e: React.FormEvent) => void; cancel: () => void }) { return <form className="product-form event-form" onSubmit={submit}><h3>{editing ? "Edit product" : "Create product"}</h3><label>Name<input value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} required /></label><label>Myanmar name<input lang="my" value={value.nameMy || ""} onChange={(e) => setValue({ ...value, nameMy: e.target.value })} /></label><label>Myanmar description<textarea lang="my" value={value.descriptionMy || ""} onChange={(e) => setValue({ ...value, descriptionMy: e.target.value })} /></label><label>Category<select value={value.category} onChange={(e) => setValue({ ...value, category: e.target.value })}>{categories.map((x) => <option key={x}>{x}</option>)}</select></label><label>Price<input value={value.price} onChange={(e) => setValue({ ...value, price: e.target.value })} required /></label><label>Product description<textarea value={value.description || ""} onChange={(e) => setValue({ ...value, description: e.target.value })} placeholder="Describe the material, craft and use" required /></label><label>Sizes</label><div className="size-picker">{["S", "M", "L"].map((s) => <button type="button" key={s} className={value.sizes.includes(s) ? "chosen" : ""} onClick={() => setValue({ ...value, sizes: value.sizes.includes(s) ? value.sizes.filter((x) => x !== s) : [...value.sizes, s] })}>{s}</button>)}</div><label>Image URL<input value={value.image.startsWith("data:") ? "" : value.image} onChange={(e) => setValue({ ...value, image: e.target.value })} /></label><label>Or upload image<input type="file" accept="image/*" onChange={(e) => chooseImage(e.target.files?.[0])} /></label>{value.image && <img className="event-preview" src={value.image} alt="Preview" />}<button className="gold-button"><ImagePlus size={17} /> {editing ? "Save product" : "Create product"}</button>{editing && <button type="button" onClick={cancel}>Cancel</button>}</form>; }
function EventForm({ value, setValue, chooseImage, submit, editing, cancel }: { value: EventPost; setValue: (x: EventPost) => void; chooseImage: (x?: File) => void; submit: (e: React.FormEvent) => void; editing: boolean; cancel: () => void }) { return <form className="product-form event-form" onSubmit={submit}><label>Title<input value={value.title} onChange={(e) => setValue({ ...value, title: e.target.value })} required /></label><label>Date / location<input value={value.date} onChange={(e) => setValue({ ...value, date: e.target.value })} required /></label><label>Button label<input value={value.button} onChange={(e) => setValue({ ...value, button: e.target.value })} /></label><label>Image URL<input value={value.image.startsWith("data:") ? "" : value.image} onChange={(e) => setValue({ ...value, image: e.target.value })} /></label><label>Or upload image<input type="file" accept="image/*" onChange={(e) => chooseImage(e.target.files?.[0])} /></label>{value.image && <img className="event-preview" src={value.image} alt="Preview" />}<button className="gold-button"><ImagePlus size={17} /> {editing ? "Save event" : "Publish event"}</button>{editing && <button type="button" onClick={cancel}>Cancel</button>}</form>; }
function OrderList({ rows, choose }: { rows: Order[]; choose: (x: Order) => void }) { return <div className="order-list">{rows.map((x) => <button className="order-row" onClick={() => choose(x)} key={x.id}><span><b>{x.id}</b> · {x.customer}</span><em>{x.status}</em><Eye size={17} /></button>)}</div>; }
function OrderModal({ order, close, save, remove }: { order: Order; close: () => void; save: (x: Order) => void; remove: () => void }) { const [draft, setDraft] = useState(order); return <div className="modal-backdrop"><div className="order-detail"><button className="close" onClick={close}><X /></button><p className="eyebrow">ORDER DETAIL · {draft.id}</p><h2>{draft.customer}</h2><div className="order-product"><img src={draft.image} alt={draft.item} /><b>{draft.item}</b></div><div><span>Phone</span><b>{draft.phone}</b></div><div><span>Address</span><b>{draft.address}</b></div><label>Status<select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value })}><option>Pending payment</option><option>Confirmed</option><option>Ready for delivery</option><option>Completed</option></select></label><div><span>Total</span><b>{draft.total}</b></div><button className="gold-button" onClick={() => save(draft)}>Save order</button><button className="delete-button" onClick={remove}>Delete order</button></div></div>; }
function Fields({ data, update }: { data: Record<string, string>; update: (k: string, v: string) => void }) { return <>{Object.entries(data).map(([key, value]) => <label key={key}>{key.replace(/([A-Z])/g, " $1")}{value.length > 70 ? <textarea value={value} onChange={(e) => update(key, e.target.value)} /> : <input value={value} onChange={(e) => update(key, e.target.value)} />}</label>)}</>; }
function HeroImages({ images, update, upload }: { images: string[]; update: (images: string[]) => void; upload: (file: File | undefined, index: number) => void }) { const slots = Array.from({ length: 4 }, (_, index) => images[index] || ""); const change = (index: number, value: string) => { const next = [...slots]; next[index] = value; update(next); }; return <div className="hero-image-manager"><h3>Home carousel images</h3><p>Use up to 4 images. They rotate automatically on the storefront.</p><div>{slots.map((image, index) => <label key={index}>Image {index + 1}<input value={image.startsWith("data:") ? "" : image} placeholder="Image URL" onChange={(e) => change(index, e.target.value)} /><input type="file" accept="image/*" onChange={(e) => upload(e.target.files?.[0], index)} />{image && <img src={image} alt={`Carousel preview ${index + 1}`} />}</label>)}</div></div>; }
