import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const base=process.env.ADMIN_TEST_URL || 'http://127.0.0.1:8788';
const password=readFileSync(new URL('../.sites-runtime/admin-credentials.txt',import.meta.url),'utf8').match(/^Password: (.+)$/m)[1];
const call=async(path,{method='GET',data,cookie,origin=base}={})=>fetch(base+path,{method,headers:{...(data!==undefined?{'Content-Type':'application/json',Origin:origin}:{}),...(cookie?{Cookie:cookie}:{})},body:data!==undefined?JSON.stringify(data):undefined});
let response=await call('/api/storefront');assert.equal(response.status,200);assert.equal('orders' in (await response.json()).data,false);
assert.equal((await call('/api/admin/state')).status,401);
assert.equal((await call('/api/admin/resources/catalog',{method:'PUT',data:{data:[],revision:0}})).status,401);
assert.equal((await call('/api/admin/login',{method:'POST',data:{username:'admin',password},origin:'https://attacker.invalid'})).status,403);
assert.equal((await call('/api/admin/login',{method:'POST',data:{username:'admin',password:'wrong-password'}})).status,401);
response=await call('/api/admin/login',{method:'POST',data:{username:'admin',password}});assert.equal(response.status,200);
const setCookie=response.headers.get('set-cookie');for(const attribute of ['HttpOnly','Secure','SameSite=Strict','Path=/'])assert.ok(setCookie.includes(attribute));
const cookie=setCookie.split(';')[0];
response=await call('/api/admin/state',{cookie});assert.equal(response.status,200);let state=await response.json();
assert.deepEqual(state.data.orders,[]);
const original=state.data.catalog;const edited=structuredClone(original);edited[0].name+=' [persistence test]';
response=await call('/api/admin/resources/catalog',{cookie,method:'PUT',data:{data:edited,revision:state.revisions.catalog}});assert.equal(response.status,200);let revision=(await response.json()).revision;
response=await call('/api/storefront');assert.equal((await response.json()).data.catalog[0].name,edited[0].name);
response=await call('/api/admin/resources/catalog',{cookie,method:'PUT',data:{data:original,revision:state.revisions.catalog}});assert.equal(response.status,409);
const invalid=structuredClone(original);invalid[0].image='javascript:alert(1)';
assert.equal((await call('/api/admin/resources/catalog',{cookie,method:'PUT',data:{data:invalid,revision}})).status,400);
response=await call('/api/admin/resources/catalog',{cookie,method:'PUT',data:{data:original,revision}});assert.equal(response.status,200);
assert.equal((await call('/api/admin/logout',{cookie,method:'POST',data:{}})).status,200);
assert.equal((await call('/api/admin/state',{cookie})).status,401);
for(let i=0;i<5;i++)assert.equal((await call('/api/admin/login',{method:'POST',data:{username:'admin',password:'wrong-password'}})).status,401);
assert.equal((await call('/api/admin/login',{method:'POST',data:{username:'admin',password:'wrong-password'}})).status,429);
for(const path of ['/%61dmin','/api/%61dmin/state','/.env','/.git/config','/test.map'])assert.equal((await call(path)).status,404);
console.log('PASS: authentication, secure cookies, CSRF, persistent CMS data, public privacy, version conflicts, image validation, logout revocation, encoded routes, login rate limit.');
