"use client";
import { useLanguage } from "@/components/language-provider";
import Link from "next/link";
import { textLanguage } from "@/lib/typography";
import { ArrowRight } from "lucide-react";
import { useEffect, useState } from "react";
import { Cards, Footer, Header } from "@/components/store-shell";
import { defaultContent, defaultEvents, readContent, readEvents, type EventPost, type StoreContent } from "@/lib/store-content";
export function HomeContent() { const { language, version, t } = useLanguage(); const [content, setContent] = useState<StoreContent>(defaultContent); const [slide, setSlide] = useState(0); useEffect(() => { const refresh = () => setContent(readContent(language)); refresh(); window.addEventListener("storage", refresh); return () => window.removeEventListener("storage", refresh); }, [language, version]); const home = content.home; const images = home.heroImages.filter(Boolean); useEffect(() => { setSlide(0); if (images.length < 2) return; const timer = window.setInterval(() => setSlide((current) => (current + 1) % images.length), 4800); return () => window.clearInterval(timer); }, [images.length]); return <main><Header /><section className="hero motion-in"><div className="hero-copy"><p className="eyebrow">{home.eyebrow}</p><h1 lang={textLanguage(home.title, home.accent)}>{home.title}<br /><em>{home.accent}</em></h1><p className="intro">{home.intro}</p><Link className="gold-button" href="/collection">{home.cta} <ArrowRight size={18} /></Link></div><div className="hero-image" aria-label="Showroom gallery">{images.map((image, index) => <img className={index === slide ? "active" : ""} src={image} alt="Uk Sein furniture" key={image} />)}<div className="hero-dots">{images.map((_, index) => <button aria-label={`Show image ${index + 1}`} className={index === slide ? "active" : ""} onClick={() => setSlide(index)} key={index} />)}</div></div></section><section className="shop"><div className="section-head"><div><p className="eyebrow">{home.collectionEyebrow}</p><h2 lang={textLanguage(home.collectionHeading)}>{home.collectionHeading}</h2></div><Link className="text-link" href="/collection">{t("View all")} <ArrowRight size={17} /></Link></div><Cards /></section><Footer /></main>; }
export function AboutContent() { const { language, version } = useLanguage(); const [content, setContent] = useState<StoreContent>(defaultContent); useEffect(() => setContent(readContent(language)), [language, version]); const about = content.about; const values = [["01", about.value1Title, about.value1Text], ["02", about.value2Title, about.value2Text], ["03", about.value3Title, about.value3Text]]; return <main><Header /><section className="about-hero motion-in"><div><p className="eyebrow">{about.eyebrow}</p><h1 lang={textLanguage(about.title, about.accent)}>{about.title}<br /><em>{about.accent}</em></h1><p>{about.intro}</p></div><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85" alt="Crafted interior" /></section><section className="values">{values.map(([number, title, text]) => <div key={number}><b>{number}</b><h2 lang={textLanguage(title)}>{title}</h2><p>{text}</p></div>)}</section><Footer /></main>; }
export function EventsContent() { const { language, version } = useLanguage(); const [content, setContent] = useState<StoreContent>(defaultContent); const [events, setEvents] = useState<EventPost[]>(defaultEvents); useEffect(() => { setContent(readContent(language)); setEvents(readEvents(language)); }, [language, version]); return <main><Header /><section className="page-hero motion-in"><p className="eyebrow">{content.events.eyebrow}</p><h1 lang={textLanguage(content.events.title)}>{content.events.title}</h1><p>{content.events.intro}</p></section><section className="events-grid">{events.map((event) => <article key={event.id}><img src={event.image} alt={event.title} /><p>{event.date}</p><h2 lang={textLanguage(event.title)}>{event.title}</h2><button type="button">{event.button}</button></article>)}</section><Footer /></main>; }
