export type Language = "en" | "my";
export const myanmar: Record<string, string> = {
  "Home": "ပင်မစာမျက်နှာ", "Collection": "ပစ္စည်းများ", "Events": "အစီအစဉ်များ", "About us": "ကျွန်ုပ်တို့အကြောင်း", "Contact us": "ဆက်သွယ်ရန်", "Contact Us": "ဆက်သွယ်ရန်", "Admin": "စီမံခန့်ခွဲရန်",
  "Nationwide deliveries": "တစ်နိုင်ငံလုံး ပို့ဆောင်ပေးသည်", "Handcrafted locally": "ပြည်တွင်း၌ လက်မှုဖြင့်ပြုလုပ်သည်", "Nationwide deliveries and handcrafted locally": "ပြည်တွင်းလက်မှုပစ္စည်းများကို တစ်နိုင်ငံလုံးပို့ဆောင်ပေးသည်",
  "Search products": "ပစ္စည်းရှာရန်", "Shopping bag": "ဈေးဝယ်အိတ်", "NEW": "အသစ်", "View details": "အသေးစိတ်ကြည့်ရန်", "View all": "အားလုံးကြည့်ရန်",
  "Seating": "ထိုင်ခုံများ", "Tables": "စားပွဲများ", "Decor": "အလှဆင်ပစ္စည်းများ", "All products": "ပစ္စည်းအားလုံး", "Product categories": "ပစ္စည်းအမျိုးအစားများ", "Available sizes": "ရရှိနိုင်သောအရွယ်အစားများ",
  "Cocoon Hanging Chair": "ရက်တန်ကြိုးဆွဲထိုင်ခုံ", "Round Rattan Coffee Table": "ရက်တန်စားပွဲဝိုင်း", "Sunburst Wall Mirror": "နေရောင်ခြည်ပုံ နံရံကပ်မှန်", "Cane Lounge Chair": "ကြိမ်အနားယူထိုင်ခုံ",
  "A handcrafted piece made to bring natural texture and a calm, lived-in feeling to your home.": "သင့်အိမ်ကို သဘာဝအလှနှင့် အေးချမ်းနွေးထွေးမှု ပေးစွမ်းရန် လက်မှုဖြင့်ပြုလုပ်ထားသော ပစ္စည်းဖြစ်ပါသည်။",
  "Search results for": "ရှာဖွေမှုရလဒ်", "found": "ခု တွေ့ရှိသည်", "No products found. Try another search term.": "ပစ္စည်းမတွေ့ပါ။ အခြားစကားလုံးဖြင့် ရှာကြည့်ပါ။", "← Back to collection": "← ပစ္စည်းများသို့ ပြန်သွားရန်", "Product not found": "ပစ္စည်းမတွေ့ပါ", "Add to basket": "ဈေးဝယ်အိတ်ထဲထည့်ရန်",
  "SHOP ALL": "ပစ္စည်းအားလုံး", "The collection": "ကျွန်ုပ်တို့၏ ပစ္စည်းများ", "Handmade pieces designed for warm, considered living.": "နွေးထွေးလှပသော အိမ်အတွက် စိတ်တိုင်းကျ ဖန်တီးထားသည့် လက်မှုပစ္စည်းများ။",
  "YANGON · MYANMAR": "ရန်ကုန် · မြန်မာ", "Made by hand.": "လက်မှုဖြင့် ဖန်တီးသည်။", "Meant for home.": "သင့်အိမ်အတွက် ရည်ရွယ်သည်။", "Thoughtful rattan furniture and local crafts for slower, warmer living.": "အေးချမ်းနွေးထွေးသော နေထိုင်မှုအတွက် ရက်တန်ပရိဘောဂနှင့် ပြည်တွင်းလက်မှုပစ္စည်းများ။", "Shop the collection": "ပစ္စည်းများကြည့်ရန်", "CURATED PIECES": "ရွေးချယ်ထားသော လက်ရာများ", "Everyday objects, beautifully made.": "နေ့စဉ်အသုံးအဆောင်များကို လှပစွာဖန်တီးထားသည်။",
  "OUR STORY": "ကျွန်ုပ်တို့အကြောင်း", "Made in Myanmar,": "မြန်မာပြည်တွင် ဖန်တီး၍", "for your home.": "သင့်အိမ်အတွက် ရည်ရွယ်သည်။", "Uk Sein celebrates natural materials and the enduring skill of local craft.": "ဦးစိန်သည် သဘာဝကုန်ကြမ်းများနှင့် ပြည်တွင်းလက်မှုပညာ၏ တန်ဖိုးကို မြှင့်တင်ပေးပါသည်။",
  "Local makers": "ပြည်တွင်းလက်မှုပညာရှင်များ", "We celebrate the techniques makers keep alive.": "လက်မှုပညာရှင်များ ထိန်းသိမ်းလာသည့် နည်းပညာများကို တန်ဖိုးထားပါသည်။", "Natural materials": "သဘာဝကုန်ကြမ်းများ", "Rattan, cane and wood bring calm to a home.": "ရက်တန်၊ ကြိမ်နှင့် သစ်သားတို့က အိမ်ကို အေးချမ်းစေပါသည်။", "Built to stay": "ရေရှည်အသုံးပြုရန်", "Pieces for a home that evolves with you.": "သင့်ဘဝနှင့်အတူ ပြောင်းလဲတိုးတက်သည့် အိမ်အတွက် ပစ္စည်းများ။",
  "IN THE SHOWROOM": "ပြခန်းအစီအစဉ်များ", "Events & workshops": "အစီအစဉ်နှင့် အလုပ်ရုံဆွေးနွေးပွဲများ", "Join us for maker conversations, styling sessions, and seasonal collections.": "လက်မှုပညာရှင်များနှင့် ဆွေးနွေးပွဲ၊ အိမ်အလှဆင်အစီအစဉ်နှင့် ရာသီအလိုက်ပစ္စည်းပြပွဲများတွင် ပါဝင်ပါ။", "Rattan care workshop": "ရက်တန်ပစ္စည်း ထိန်းသိမ်းနည်းသင်တန်း", "Holiday home styling": "အားလပ်ရက် အိမ်အလှဆင်အစီအစဉ်", "Reserve a place": "နေရာကြိုတင်စာရင်းပေးရန်", "24 NOVEMBER · YANGON": "နိုဝင်ဘာ ၂၄ · ရန်ကုန်", "8 DECEMBER · SHOWROOM": "ဒီဇင်ဘာ ၈ · ပြခန်း",
  "Showroom": "ပြခန်း", "Contact": "ဆက်သွယ်ရန်", "No. 5, Nawaday Street": "အမှတ် ၅၊ နဝဒေးလမ်း", "Yangon, Myanmar": "ရန်ကုန်၊ မြန်မာ",
  "GET IN TOUCH": "ဆက်သွယ်ရန်", "Contact Uk Sein": "ဦးစိန်ကို ဆက်သွယ်ရန်", "We would love to help you find the right piece for your home.": "သင့်အိမ်အတွက် သင့်တော်သည့်ပစ္စည်းကို ရွေးချယ်ရာတွင် ကူညီပေးလိုပါသည်။", "Back to home": "ပင်မစာမျက်နှာသို့ ပြန်ရန်", "Call us": "ဖုန်းဆက်ရန်", "Email us": "အီးမေးလ်ပို့ရန်", "Request a callback": "ဖုန်းပြန်ခေါ်ပေးရန်", "Select a time": "အချိန်ရွေးရန်", "Request a quote": "ဈေးနှုန်းတောင်းရန်", "Discuss your requirements": "လိုအပ်ချက်များ ဆွေးနွေးရန်", "Product brochure": "ပစ္စည်းမိတ်ဆက်စာစောင်", "Download PDF or view online": "PDF ရယူရန် သို့မဟုတ် အွန်လိုင်းကြည့်ရန်",
};
