import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
const timestamps={createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)};
export const categories=sqliteTable("categories",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),slug:text("slug").notNull().unique(),...timestamps});
export const products=sqliteTable("products",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),slug:text("slug").notNull().unique(),categoryId:integer("category_id").references(()=>categories.id),price:integer("price").notNull(),description:text("description").notNull().default(""),imageUrl:text("image_url").notNull().default(""),sizes:text("sizes").notNull().default("[]"),active:integer("active",{mode:"boolean"}).notNull().default(true),...timestamps});
export const orders=sqliteTable("orders",{id:integer("id").primaryKey({autoIncrement:true}),reference:text("reference").notNull().unique(),customerName:text("customer_name").notNull(),phone:text("phone").notNull(),address:text("address").notNull(),items:text("items").notNull(),total:integer("total").notNull(),paymentMethod:text("payment_method").notNull(),status:text("status").notNull().default("pending"),...timestamps});
export const siteContent=sqliteTable("site_content",{id:integer("id").primaryKey({autoIncrement:true}),key:text("key").notNull().unique(),english:text("english").notNull().default(""),myanmar:text("myanmar").notNull().default(""),...timestamps});
export const events=sqliteTable("events",{id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),eventDate:text("event_date").notNull(),description:text("description").notNull().default(""),imageUrl:text("image_url").notNull().default(""),active:integer("active",{mode:"boolean"}).notNull().default(true),...timestamps});
export const contactDetails=sqliteTable("contact_details",{id:integer("id").primaryKey({autoIncrement:true}),kind:text("kind").notNull().unique(),label:text("label").notNull(),value:text("value").notNull(),detail:text("detail").notNull().default(""),...timestamps});
